name: integration-tests

on:
  push:
    paths:
      - ".github/workflows/integration-tests.yml"
  workflow_dispatch: # manual

jobs:
  generate:
    outputs:
      RANDOM_PASSWORD: ${{ env.RANDOM_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: echo "RANDOM_PASSWORD=$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 12)" >> "$GITHUB_ENV"
      - run: echo "$RANDOM_PASSWORD / ${{ env.RANDOM_PASSWORD }}"
      - run: env | sort
      # - run: mysql ... -p $RANDOM_PASSWORD
  testing:
    runs-on: ubuntu-latest
    needs: generate
    container: #job container with mysql client
      image: mysql:8.4
    services:
      mysqlserver: #server container with mysql server
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ needs.generate.outputs.RANDOM_PASSWORD }}
          MYSQL_DATABASE: foothebar
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        # the job container will not run until the server is ready, made sure with the options above
    steps:
      - run: echo "${{ needs.generate.outputs.RANDOM_PASSWORD }}"
      - run: mysql --version
      - run: mysql -h mysqlserver -u root -p"${{ needs.generate.outputs.RANDOM_PASSWORD }}" -e "SHOW DATABASES;"
      - run: echo "job.services=${{ toJson(job.services) }}"
      - run: echo "job.container=${{ toJson(job.container) }}"
